// Generated by fixie at 08-09-2024 21:30
package fixie

private const val RAW_ONE: UShort = 1000u

@JvmInline
value class FixDensity private constructor(val raw: UShort) : Comparable<FixDensity> {

	override fun toString(): String {
		val intPart = raw / RAW_ONE
		var fractPart = (raw % RAW_ONE).toString().replace("-", "")
		while (fractPart.length < 3) fractPart = "0$fractPart"
		fractPart = ".$fractPart"
		while (fractPart.endsWith('0')) fractPart = fractPart.substring(0 until fractPart.length - 1)
		if (fractPart == ".") fractPart = ""
		return "$intPart$fractPart"
	}

	fun toInt() = (raw / RAW_ONE).toInt()

	fun toLong() = (raw / RAW_ONE).toLong()

	fun toFloat() = toDouble().toFloat()

	fun toDouble() = raw.toDouble() / RAW_ONE.toDouble()

	operator fun plus(right: FixDensity) = FixDensity((this.raw + right.raw).toUShort())

	operator fun plus(right: Int) = this + from(right)

	operator fun plus(right: Long) = this + from(right)

	operator fun plus(right: Float) = this + from(right)

	operator fun plus(right: Double) = this + from(right)

	operator fun minus(right: FixDensity) = FixDensity((this.raw - right.raw).toUShort())

	operator fun minus(right: Int) = this - from(right)

	operator fun minus(right: Long) = this - from(right)

	operator fun minus(right: Float) = this - from(right)

	operator fun minus(right: Double) = this - from(right)

	operator fun times(right: FixDensity): FixDensity {
		val largeValue = this.raw.toUInt() * right.raw.toUInt()
		return FixDensity((largeValue / RAW_ONE).toUShort())
	}

	operator fun times(right: Int) = FixDensity((raw * right.toUInt()).toUShort())

	operator fun times(right: Long) = FixDensity((raw * right.toULong()).toUShort())

	operator fun times(right: Float) = this * from(right)

	operator fun times(right: Double) = this * from(right)

	operator fun div(right: FixDensity): FixDensity {
		val largeValue = this.raw.toUInt() * RAW_ONE.toUInt()
		return FixDensity((largeValue / right.raw).toUShort())
	}

	operator fun div(right: Int) = FixDensity((raw / right.toUInt()).toUShort())

	operator fun div(right: Long) = FixDensity((raw / right.toULong()).toUShort())

	operator fun div(right: Float) = this / from(right)

	operator fun div(right: Double) = this / from(right)

	override operator fun compareTo(other: FixDensity) = this.raw.compareTo(other.raw)

	operator fun compareTo(other: Short) = if (other < 0) 1 else if (other > 65) -1 else this.compareTo(from(other))

	operator fun compareTo(other: UShort) = if (other > 65u) -1 else this.compareTo(from(other))

	operator fun compareTo(other: Int) = if (other < 0) 1 else if (other > 65) -1 else this.compareTo(from(other))

	operator fun compareTo(other: UInt) = if (other > 65u) -1 else this.compareTo(from(other))

	operator fun compareTo(other: Long) = if (other < 0) 1 else if (other > 65) -1 else this.compareTo(from(other))

	operator fun compareTo(other: ULong) = if (other > 65u) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Float) = if (other < 0.0f) 1 else if (other > 65.535f) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Double) = if (other < 0.0) 1 else if (other > 65.535) -1 else this.compareTo(from(other))

	companion object {

		val ZERO = from(0)
		val ONE = from(1)

		fun raw(rawValue: UShort) = FixDensity(rawValue)

		fun from(value: Short) = FixDensity((value.toUShort() * RAW_ONE).toUShort())

		fun from(value: Int) = from(value.toUShort())

		fun from(value: Long) = from(value.toUShort())

		fun from(value: UShort) = FixDensity((value * RAW_ONE).toUShort())

		fun from(value: UInt) = from(value.toUShort())

		fun from(value: ULong) = from(value.toUShort())

		fun from(value: Float) = from(value.toDouble())

		fun from(value: Double) = FixDensity(kotlin.math.floor(RAW_ONE.toDouble() * value + 0.5).toUInt().toUShort())
	}

	@JvmInline
	@OptIn(ExperimentalUnsignedTypes::class)
	value class Array private constructor(val raw: UShortArray) {

		constructor(size: Int) : this(UShortArray(size))

		constructor(size: Int, initializer: (Int) -> FixDensity) : this(UShortArray(size) { index -> initializer(index).raw })

		val size: Int
			get() = raw.size

		operator fun get(index: Int) = FixDensity(raw[index])

		operator fun set(index: Int, value: FixDensity) {
			raw[index] = value.raw
		}

		fun fill(value: FixDensity) {
			raw.fill(value.raw)
		}
	}
}

operator fun Int.plus(right: FixDensity) = FixDensity.from(this) + right

operator fun Long.plus(right: FixDensity) = FixDensity.from(this) + right

operator fun Float.plus(right: FixDensity) = FixDensity.from(this) + right

operator fun Double.plus(right: FixDensity) = FixDensity.from(this) + right

operator fun Int.minus(right: FixDensity) = FixDensity.from(this) - right

operator fun Long.minus(right: FixDensity) = FixDensity.from(this) - right

operator fun Float.minus(right: FixDensity) = FixDensity.from(this) - right

operator fun Double.minus(right: FixDensity) = FixDensity.from(this) - right

operator fun Int.times(right: FixDensity) = right * this

operator fun Long.times(right: FixDensity) = right * this

operator fun Float.times(right: FixDensity) = right * this

operator fun Double.times(right: FixDensity) = right * this

operator fun Int.div(right: FixDensity) = FixDensity.from(this) / right

operator fun Long.div(right: FixDensity) = FixDensity.from(this) / right

operator fun Float.div(right: FixDensity) = FixDensity.from(this) / right

operator fun Double.div(right: FixDensity) = FixDensity.from(this) / right

operator fun Int.compareTo(right: FixDensity) = FixDensity.from(this).compareTo(right)

operator fun Long.compareTo(right: FixDensity) = FixDensity.from(this).compareTo(right)

operator fun Float.compareTo(right: FixDensity) = FixDensity.from(this).compareTo(right)

operator fun Double.compareTo(right: FixDensity) = FixDensity.from(this).compareTo(right)

fun min(a: FixDensity, b: FixDensity) = FixDensity.raw(min(a.raw, b.raw))

fun max(a: FixDensity, b: FixDensity) = FixDensity.raw(max(a.raw, b.raw))
