// Generated by fixie at 08-09-2024 21:30
package fixie

import java.lang.Math.*

private const val RAW_ONE = 100000

@JvmInline
value class FixDisplacement private constructor(val raw: Int) : Comparable<FixDisplacement> {

	override fun toString(): String {
		val intPart = raw / RAW_ONE
		var fractPart = (raw % RAW_ONE).toString().replace("-", "")
		while (fractPart.length < 5) fractPart = "0$fractPart"
		fractPart = ".$fractPart"
		while (fractPart.endsWith('0')) fractPart = fractPart.substring(0 until fractPart.length - 1)
		if (fractPart == ".") fractPart = ""
		val minus = if (raw < 0 && intPart == 0) "-" else ""
		return "$minus$intPart$fractPart"
	}

	fun toInt() = raw / RAW_ONE

	fun toLong() = (raw / RAW_ONE).toLong()

	fun toFloat() = toDouble().toFloat()

	fun toDouble() = raw.toDouble() / RAW_ONE.toDouble()

	operator fun unaryMinus() = FixDisplacement(-raw)

	operator fun plus(right: FixDisplacement) = FixDisplacement(this.raw + right.raw)

	operator fun plus(right: Int) = this + from(right)

	operator fun plus(right: Long) = this + from(right)

	operator fun plus(right: Float) = this + from(right)

	operator fun plus(right: Double) = this + from(right)

	operator fun minus(right: FixDisplacement) = FixDisplacement(this.raw - right.raw)

	operator fun minus(right: Int) = this - from(right)

	operator fun minus(right: Long) = this - from(right)

	operator fun minus(right: Float) = this - from(right)

	operator fun minus(right: Double) = this - from(right)

	operator fun times(right: FixDisplacement): FixDisplacement {
		val largeValue = this.raw.toLong() * right.raw.toLong()
		return FixDisplacement((largeValue / RAW_ONE).toInt())
	}

	operator fun times(right: Int) = FixDisplacement(raw * right)

	operator fun times(right: Long) = FixDisplacement((raw * right).toInt())

	operator fun times(right: Float) = this * from(right)

	operator fun times(right: Double) = this * from(right)

	operator fun div(right: FixDisplacement): FixDisplacement {
		val largeValue = this.raw.toLong() * RAW_ONE.toLong()
		return FixDisplacement((largeValue / right.raw).toInt())
	}

	operator fun div(right: Int) = FixDisplacement(raw / right)

	operator fun div(right: Long) = FixDisplacement((raw / right).toInt())

	operator fun div(right: Float) = this / from(right)

	operator fun div(right: Double) = this / from(right)

	override operator fun compareTo(other: FixDisplacement) = this.raw.compareTo(other.raw)

	operator fun compareTo(other: Int) = if (other < -21474) 1 else if (other > 21474) -1 else this.compareTo(from(other))

	operator fun compareTo(other: Long) = if (other < -21474) 1 else if (other > 21474) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Float) = if (other < -21474.836f) 1 else if (other > 21474.836f) -1 else this.compareTo(from(other))
	operator fun compareTo(other: Double) = if (other < -21474.83648) 1 else if (other > 21474.83647) -1 else this.compareTo(from(other))

	companion object {

		val ZERO = from(0)
		val ONE = from(1)

		fun raw(rawValue: Int) = FixDisplacement(rawValue)

		fun from(value: Int) = FixDisplacement(value * RAW_ONE)

		fun from(value: Long) = from(value.toInt())

		fun from(value: Float) = from(value.toDouble())

		fun from(value: Double) = FixDisplacement(round(RAW_ONE.toDouble() * value).toInt())
	}

	@JvmInline
	value class Array private constructor(val raw: IntArray) {

		constructor(size: Int) : this(IntArray(size))

		constructor(size: Int, initializer: (Int) -> FixDisplacement) : this(IntArray(size) { index -> initializer(index).raw })

		val size: Int
			get() = raw.size

		operator fun get(index: Int) = FixDisplacement(raw[index])

		operator fun set(index: Int, value: FixDisplacement) {
			raw[index] = value.raw
		}

		fun fill(value: FixDisplacement) {
			raw.fill(value.raw)
		}
	}
}

operator fun Int.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

operator fun Long.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

operator fun Float.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

operator fun Double.plus(right: FixDisplacement) = FixDisplacement.from(this) + right

operator fun Int.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

operator fun Long.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

operator fun Float.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

operator fun Double.minus(right: FixDisplacement) = FixDisplacement.from(this) - right

operator fun Int.times(right: FixDisplacement) = right * this

operator fun Long.times(right: FixDisplacement) = right * this

operator fun Float.times(right: FixDisplacement) = right * this

operator fun Double.times(right: FixDisplacement) = right * this

operator fun Int.div(right: FixDisplacement) = FixDisplacement.from(this) / right

operator fun Long.div(right: FixDisplacement) = FixDisplacement.from(this) / right

operator fun Float.div(right: FixDisplacement) = FixDisplacement.from(this) / right

operator fun Double.div(right: FixDisplacement) = FixDisplacement.from(this) / right

operator fun Int.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

operator fun Long.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

operator fun Float.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

operator fun Double.compareTo(right: FixDisplacement) = FixDisplacement.from(this).compareTo(right)

fun abs(value: FixDisplacement) = FixDisplacement.raw(kotlin.math.abs(value.raw))

fun min(a: FixDisplacement, b: FixDisplacement) = FixDisplacement.raw(kotlin.math.min(a.raw, b.raw))

fun max(a: FixDisplacement, b: FixDisplacement) = FixDisplacement.raw(kotlin.math.max(a.raw, b.raw))
